image: jangmys/manylinux2014_pyparadiseo:latest

stages:
    - build
    - test
    - deploy
    - package

build-job:
    stage: build
    script:
        - python3 setup.py sdist bdist_wheel
    artifacts:
        paths:
            - dist/

test-job1:
    stage: test
    dependencies:
        - build-job
    artifacts:
        paths:
            - dist/
    script:
        - python3 -m pip install dist/*.whl --user --force-reinstall
        - python3 -c "import pyparadiseo"
        - python3 -m pytest tests

deploy-prod:
    stage: deploy
    script:
        - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."

package:
    stage: package
    script: cat file1.txt file2.txt | gzip > packaged.gz
    artifacts:
        paths:
            - packaged.gz
