image: jangmys/manylinux2014_pyparadiseo:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
        - .pip
        - /opt/venv/
        - _skbuild

before_script:
    - /opt/python/cp36-cp36m/bin/python3 --version  # For debugging
    - /opt/python/cp36-cp36m/bin/python3 -m venv /opt/venv
    - . /opt/venv/bin/activate
    - mkdir -p .pip
    - python3 -m pip install --cache-dir=.pip --upgrade pip
    - python3 -m pip install --cache-dir=.pip scikit-build numpy numba pytest auditwheel sphinxcontrib-napoleon
    - yum -y install python-sphinx

stages:
    - build
    - test
    - deploy

build-job:
    stage: build
    script:
        - python3 setup.py sdist bdist_wheel -G"Unix Makefiles"
        - auditwheel repair dist/*.whl
        - rm dist/*
        # - python3 -m pip install wheelhouse/*.manylinux2014_x86_64.whl
        # - python3 -c "import pyparadiseo"
        # - python3 -m pytest tests
    cache:
        paths:
            - _skbuild/
    artifacts:
        paths:
            - _skbuild/
            - wheelhouse/


test-job1:
    stage: test
    needs:
        - build-job
    script:
        - python3 -m pip install wheelhouse/*.manylinux2014_x86_64.whl
        - python3 -c "import pyparadiseo"
        - python3 -m pytest tests
        - cd docs
        - make html
    artifacts:
        paths:
            - wheelhouse/
            - docs/build/html

pages:
    stage: build
    needs:
        - build-job
    script:
        - mkdir .public
        - cp -r docs/build/html .public
        - mv .public public
    artifacts:
        paths:
            - public
    only:
        - main


pypi:
    stage: deploy
    needs:
        - test-job1
    script:
        - python3 -m pip install -U twine
        #- twine upload --skip-existing wheelhouse/*
        - twine upload wheelhouse/*.manylinux2014_x86_64.whl
    when: manual
