image: jangmys/manylinux2014_pyparadiseo:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
        - .pip
        - /opt/venv/
        - _skbuild

before_script:
    - echo "before script"
    # - /opt/python/cp36-cp36m/bin/python3 -m venv /opt/venv36
    # - . /opt/venv36/bin/activate
    # - python3 --version  # For debugging
    # - mkdir -p .pip
    # - python3 -m pip install --cache-dir=.pip --upgrade pip
    # - python3 -m pip install --cache-dir=.pip scikit-build numpy numba pytest auditwheel sphinxcontrib-napoleon Sphinx sphinx-rtd-theme pydata-sphinx-theme
    #- yum -y install python-sphinx

stages:
    - build
    - test
    - deploy

build-job:
    stage: build
    tags:
        - ci.inria.fr
        - small
    script:
        - . /opt/venv36/bin/activate
        - python3 --version
        - python3 setup.py sdist bdist_wheel -G"Unix Makefiles"
        - auditwheel repair dist/*cp36m-linux_x86_64.whl
        - rm dist/*
        # - python3 -m pip install wheelhouse/*.manylinux2014_x86_64.whl
        # - python3 -c "import pyparadiseo"
        # - python3 -m pytest tests
    cache:
        paths:
            - _skbuild/
    artifacts:
        paths:
            #- _skbuild/
            - wheelhouse/


build-cp37:
    stage: build
    tags:
        - ci.inria.fr
        - small
    script:
        - /opt/python/cp37-cp37m/bin/python3 -m venv /opt/venv37
        - . /opt/venv37/bin/activate
        - python3 --version  # For debugging
        - mkdir -p .pip
        - python3 -m pip install --cache-dir=.pip --upgrade pip
        - python3 -m pip install --cache-dir=.pip scikit-build numpy numba pytest auditwheel sphinxcontrib-napoleon Sphinx sphinx-rtd-theme pydata-sphinx-theme
        - python3 setup.py sdist bdist_wheel -G"Unix Makefiles"
        - auditwheel repair dist/*cp37m-linux_x86_64.whl
        - rm dist/*
        # - python3 -m pip install wheelhouse/*.manylinux2014_x86_64.whl
        # - python3 -c "import pyparadiseo"
        # - python3 -m pytest tests
    cache:
        paths:
            - _skbuild/
    artifacts:
        paths:
            #- _skbuild/
            - wheelhouse/
    when: manual


test-job1:
    stage: test
    tags:
        - ci.inria.fr
        - small
    needs:
        - build-job
    script:
        - . /opt/venv36/bin/activate
        - python3 -m pip install wheelhouse/*.manylinux2014_x86_64.whl
        - python3 -c "import pyparadiseo"
        - python3 -m pytest tests
    artifacts:
        paths:
            - wheelhouse/
            - docs/build/

pages:
    stage: test
    tags:
    - ci.inria.fr
    - small
    needs:
        - test-job1
    script:
        - cd docs
        - make html
        - cd ..
        - mkdir .public
        - ls
        - ls docs
        - ls docs/build
        - cp -r docs/build/* .public
        - mv .public public
        - ls public
    artifacts:
        paths:
            - public
    when: manual



pypi:
    stage: deploy
    tags:
        - ci.inria.fr
        - small
    needs:
        - test-job1
    script:
        - python3 -m pip install -U twine
        #- twine upload --skip-existing wheelhouse/*
        - twine upload wheelhouse/*.manylinux2014_x86_64.whl
    when: manual
