[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cmake>=3.12",
    "scikit-build>=0.12",
    "ninja"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["tests"]
