from ..._core import eoWeakElitistReplacement as WeakElitistReplacement
from ..._core import eoMergeReduce as MergeReduce
from ..._core import eoPlusReplacement as PlusReplacement
from ..._core import eoCommaReplacement as CommaReplacement
from ..._core import eoEPReplacement as EPReplacement
from ..._core import eoReduceMerge as ReduceMerge
from ..._core import eoSSGAWorseReplacement as SSGAWorseReplacement
from ..._core import eoSSGADetTournamentReplacement as SGADetTournamentReplacement
from ..._core import eoSSGAStochTournamentReplacement as SSGAStochTournamentReplacement
from ..._core import eoMGGReplacement as MGGReplacement
